import './Banner.css';

const Banner = () => {
    return (
        <div className="banner">
            <p>LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! LIKE WHAT YOU SEE? ADD TO CART? BUY NOW! </p>
        </div>
    );
}

export default Banner;
